= [WIP] Dart Plugin for Eclipse

An eclipse plugin for https://www.dartlang.org/[Dart] and https://flutter.io[Flutter] development.
Dart is a programming language mostly used by the Flutter project.

== Documentation

- https://www.dartlang.org/guides/get-started[Getting Started with Dart]

== Development

Currently this project is highly experimental and in no way production ready.
It is based on the "new" https://github.com/dart-lang/sdk/tree/master/pkg/analysis_server[dart language server] which is also not production ready.

The language server is not released yet and the only way to obtain it is by using a https://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/[Dart nightly build].

=== Get Started

- Download the latest nightly from https://gsdview.appspot.com/dart-archive/channels/be/raw/latest/sdk/[here].
- Extract the archive.
- Copy the path and replace the `dartLocation` in `FlutterLanguageServerStreamProvider` with your location
- Start the plugin

NOTE: If you have troubles with compilation and/or running try to install the necessary dependencies as described below.

=== Installing the dependencies

For the plugin to work as expected you need to install some dependencies.

Add the update site of the `LSP4E` project: `http://download.eclipse.org/lsp4e/releases/latest/`.

Install the plugins:
- `Language Server Protocol client for Eclipse IDE (Incubation) Source`
- `Language Server Protocol client for Eclipse IDE (Incubation)`

Add the update site of the `TM4E` project: `http://download.eclipse.org/tm4e/snapshots/`.

Install the plugins:
- `TextMate Core`
- `TextMate Core Developer Resources`
